// Game constants
const GAME_WIDTH = 900;
const GAME_HEIGHT = 600;
const PLAYER_SIZE = 168; // 4x bigger than original (42 * 4)
const PLAYER_SPEED = 3.1;
const INITIAL_PICARATS = 0;
const INITIAL_HINT_COINS = 2;
const MAX_HINTS_PER_PUZZLE = 3;
const INTERACT_RADIUS = 55;

window.GAME_WIDTH = GAME_WIDTH;
window.GAME_HEIGHT = GAME_HEIGHT;
window.PLAYER_SIZE = PLAYER_SIZE;
window.PLAYER_SPEED = PLAYER_SPEED;
window.INITIAL_PICARATS = INITIAL_PICARATS;
window.INITIAL_HINT_COINS = INITIAL_HINT_COINS;
window.MAX_HINTS_PER_PUZZLE = MAX_HINTS_PER_PUZZLE;
window.INTERACT_RADIUS = INTERACT_RADIUS;